PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>

SELECT * WHERE {
    {
        ?s a ehri:RecordSet ;
            rico:thingIsSourceOfRelation ?copyRelation .
        ?copyRelation a ehri:HasCopyRelation .
        ?copy rico:thingIsTargetOfRelation ?copyRelation ;
            rico:name|rico:title ?copyName .
        BIND(IRI(
            IF(STRSTARTS(STR(?copy), "http://lod.ehri-project-test.eu/institutions/"),
                REPLACE(STR(?copy), "http://lod.ehri-project-test.eu/institutions/", "https://portal.ehri-project.eu/institutions/"),
                REPLACE(STR(?copy), "http://lod.ehri-project-test.eu/units/", "https://portal.ehri-project.eu/units/")
               )) AS ?portalLink)
    }
    UNION
    {
        ?s a ehri:RecordSet ;
            rico:thingIsTargetOfRelation ?originalRelation .
        ?originalRelation a ehri:IsCopyOfRelation .
        ?original rico:thingIsTargetOfRelation ?originalRelation ;
            rico:name|rico:title ?originalName .
        BIND(IRI(
            IF(STRSTARTS(STR(?original), "http://lod.ehri-project-test.eu/institutions/"),
                REPLACE(STR(?original), "http://lod.ehri-project-test.eu/institutions/", "https://portal.ehri-project.eu/institutions/"),
                REPLACE(STR(?original), "http://lod.ehri-project-test.eu/units/", "https://portal.ehri-project.eu/units/")
               )) AS ?portalLink)
    }
    FILTER (?s = <$archival_description_id>)
} LIMIT 10