PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>

SELECT * WHERE {
    ?s a ehri:Country ;
        rico:isOrWasLocationOfAgent ?institution .
    ?institution rico:name ?institutionName .
    BIND(IRI(REPLACE(STR(?institution), "http://lod.ehri-project-test.eu/institutions/", "https://portal.ehri-project.eu/institutions/")) AS ?portalLink)
    FILTER (?s = <$country_id>)
} LIMIT 10